# Run with `docker-compose up -d`
# to unmount volume and reinitialize schema/data, run with `docker-compose up -v`
version: '3.5'
services:
  local_db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=service_dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flyway_demo_db
      - ENVIRONMENT=local
      - POSTGRES_HOST=local_db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/oracle
    networks:
      - flyway-demo
  # Image for flyway. Waits for the database to spin up, then applies migrations in all directories under the sql folder
  flyway:
    image: flyway/flyway
    command: -connectRetries=60 -url=jdbc:postgresql://local_db/flyway_demo_db?useSSL=false -user=service_dev -password=password migrate
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf:/flyway/conf
    depends_on:
      - local_db
    networks:
      - flyway-demo
networks:
  flyway-demo:
    name: flyway_demo_network
volumes:
  db_data: